name: Update

on:
  push:
    tags:
      - 'publish*'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      FORK: '${{ github.repository_owner }}'
      USER: 'dive2Pro'
      EMAIL: 'toylucklebo@gmail.com'
      BRANCH: 'Tabs'
      EXTENSION_DIR: 'extensions/hyc'
      EXTENSION_JSON: 'extensions/hyc/Tabs+.json'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Git
        run: |
          git config --global user.name "$USER"
          git config --global user.email "$EMAIL"
      - name: Checkout roam-depot repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.FORK }}/roam-depot
          ref: main
          token: ${{ secrets.PAT }}
      - name: Sync fork
        run: |
          git fetch --prune --unshallow
          git remote add upstream "https://github.com/Roam-Research/roam-depot"
          git fetch upstream
          git checkout -B main upstream/main
          git push -f origin main

      - name: Create ${{env.BRANCH}} branch from main
        run: |
          git checkout -b ${{env.BRANCH}} origin/main

      - name: Update $EXTENSION_DIR
        run: |
          mkdir ${{ env.EXTENSION_DIR }} || true
          cat <<EOF > ${{ env.EXTENSION_JSON }}
              {
                "name": "Roam Tabs",
                "short_description": "A plugin that allows you to organize the pages you're working on into tabs.",
                "author": "hyc",
                "stripe_account": "acct_1LLkJkQbYbNOfzpa",
                "source_url": "${{github.server_url}}/${{ github.repository }}",
                "source_repo": "${{github.server_url}}/${{ github.repository }}.git",
                "source_commit": "$GITHUB_SHA"
              }            
          EOF

      - name: Commit and Push changes
        run: |
          git pull
          git add ${{ env.EXTENSION_JSON }}
          git commit -m "Update source_commit to $GITHUB_SHA"
          git push --force origin ${{ env.BRANCH }}
          
      - name: Create pull request
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const branch = "${{ env.BRANCH }}"; // Replace with the branch you want to create a PR for
            const owner = 'Roam-Research';
            const repo = 'roam-depot';
            const title = '${{ env.BRANCH }}';
            const body = '';
            const head = '${{env.FORK}}:${{env.BRANCH}}';
            const base = 'main'; // Replace with the branch you want to merge the PR into 
            try {
              const { data: pullRequest } = await github.pulls.create({
                owner,
                repo,
                title,
                body,
                head,
                base,
              });
              console.log(`PR created: ${pullRequest.html_url}`);
            } catch(e) {
              console.log('PR creating failed', e);
            }
